language: go
go:
  - 1.8
  - master
  # NOTE: no tip, see https://github.com/travis-ci/gimme/issues/38
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email: false
